services:
  - type: web
    name: gprint
    runtime: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app ./cmd/server
    startCommand: ./app
    envVars:
      - key: GO_VERSION
        value: "1.25.0"
